[package]
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Eirik Ogilvie-Wigley <eowigley@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
]
description = "Implementation of the Jubjub elliptic curve group"
documentation = "https://docs.rs/jubjub/"
homepage = "https://github.com/zkcrypto/jubjub"
license = "MIT/Apache-2.0"
name = "jubjub"
repository = "https://github.com/zkcrypto/jubjub"
version = "0.5.1"
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde-hex = "0.1.0"

[dependencies.bitvec]
version = "0.18"
default-features = false

[dependencies.bls12_381]
version = "0.3.1"
default-features = false

[dependencies.ff]
version = "0.8"
default-features = false

[dependencies.group]
version = "0.8"
default-features = false

[dependencies.rand_core]
version = "0.5"
default-features = false

[dependencies.subtle]
version = "^2.2.1"
default-features = false

[dev-dependencies]
criterion = "0.3"

[dev-dependencies.rand_xorshift]
version = "0.2"
default-features = false

[features]
default = ["alloc"]
alloc = ["group/alloc"]

[[bench]]
name = "fq_bench"
harness = false

[[bench]]
name = "fr_bench"
harness = false

[[bench]]
name = "point_bench"
harness = false
